### ISSUE TITLE
Production config line that might be responsible for Webpacker fail in Production

### ISSUE THREAD

**Issue by yannklein** [mvbennett/abandonya#71]
I am not sure what this line of code in `producction.rb` is doing, but I am 100% sure we don't needed it in a standard rails app like the one you build. Is it a fix you tried? It might be harmful for when you ask webpacker to compile the frontend in production env.
https://github.com/mvbennett/abandonya/blob/347d42afbec8207a608d0b1717dd0112f81291d6/config/environments/production.rb#L4

**Comment by mvbennett** [comment]
Yes this was actually the first fix we tried which seemingly worked, I'll get rid of it now.

**Comment by mvbennett** [comment]
after removing it and attempting to push to heroku it gives us the same error as we were dealing with before:
```
remote:        rake aborted!
remote:        SassC::SyntaxError: Error: Function rgb is missing argument $green.
remote:                on line 1 of stdin
remote:        >> tion:relative;-webkit-tap-highlight-color:rgb(0 0 0/0)}.mapboxgl-canvas{posi
```
